//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dragon.rc
//
#define IDC_MYICON                      2
#define IDOK2                           3
#define IDLOAD                          3
#define IDCANCEL2                       3
#define IDCANCEL3                       4
#define IDOK3                           4
#define IDD_DRAGON_DIALOG               102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_DRAGON                      107
#define IDI_SMALL                       108
#define IDC_DRAGON                      109
#define IDC_DRAGONRAJA_CLASS            109
#define IDS_VERSION                     110
#define ID_EDITBOX_MESSAGE              110
#define ID_CHECK_EQUIP                  110
#define ID_MESSAGE_BOX1                 111
#define ID_MESSAGE_BOX2                 112
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       133
#define IDD_DEVELOPE_ENVIR              136
#define IDD_CHECK_EQUIP                 137
#define IDD_DIALOG_ANIMATION_EDIT       138
#define IDD_DIALOG_INPUT_ITEM           139
#define IDD_INPUT_EVENT_NO              140
#define IDD_DIALOG1                     141
#define IDD_VIEW_MAPOBJECT_INFO         142
#define IDD_CHANGE_BODYRGB              143
#define IDD_VIEW_ITEMINFO               144
#define IDD_ITEM_OBJECT_CONTROL         145
#define IDD_VIEW_MAPOBJECT_INFO1        146
#define IDD_INPUT_MAP_ATTR              149
#define IDD_INPUT_SKILL                 150
#define IDD_MOUSECURSOR_HOTSPOT         152
#define IDD_INPUT_MAPOBJECT             153
#define IDD_INPUT_MYHOUSE               154
#define IDC_CURSOR1                     155
#define IDD_DIALOG2                     156
#define IDC_CURSOR2                     158
#define IDD_CHARACTER_ABILITY_SET       159
#define IDD_GENERATE_ITEM               160
#define IDD_DEVELOPE_ENVIR1             161
#define IDD_CHANGE_TACTICS              175
#define IDD_INPUT_PASSWORD              181
#define IDD_NPC_DELETE                  201
#define IDD_SKILL_EXP                   204
#define IDD_PUBLIC_MESSAGE              206
#define IDD_DIALOG3                     212
#define IDD_CHECK_EFFECT                212
#define IDD_BASIC_INFO                  213
#define IDD_WHERE_IS_HE                 214
#define IDD_PUBLIC_MESSAGE_ALL          215
#define IDD_TITLE_                      219
#define IDI_ICON2                       220
#define IDB_BITMAP2                     224
#define IDD_EVENT_TOOL                  225
#define IDC_CURSOR3                     226
#define IDR_GM                          227
#define IDD_MAP_MOVE                    228
#define IDC_CURSOR4                     228
#define IDD_SET_SCENARIO_TIME           229
#define IDD_MAP_MOVE_MULTIPLE           231
#define IDD_MONSTERMAKE                 232
#define IDD_LOCAL_WAR_SET               233
#define IDD_NATION_WAR                  234
#define IDD_PROFILE_TYPED_MSG           240
#define IDR_SECURITY1                   241
#define IDD_PLAY_SOUND                  248
#define IDD_LMS_MENU                    249
#define IDD_EXPEVENT                    250
#define IDD_MNPK                        251
#define IDD_DIALOG4                     252
#define IDD_CHECK_QUEST                 252
#define IDD_DIALOG_BanTool              254
#define IDD_BAN_TOOL                    255
#define IDD_DIALOG5                     257
#define IDD_GENERATEITEM                257
#define IDD_FORCE_START_NATION_WAR      260
#define IDR_ACCELERATOR1                263
#define IDC_RADIO1                      1001
#define IDC_RADIO_1_FEMALE              1002
#define IDC_RADIO3                      1002
#define IDC_SORT_L                      1002
#define IDC_BRUSH2                      1002
#define IDC_RADIO_FARM                  1002
#define IDC_RADIO_X                     1002
#define IDC_EDIT1_LEVEL                 1003
#define IDC_RADIO6                      1003
#define IDC_SORT_M                      1003
#define IDC_BRUSH3                      1003
#define IDC_RADIO_MINE                  1003
#define IDC_EDIT2                       1004
#define IDC_RADIO7                      1004
#define IDC_EDIT_ITEM_X                 1004
#define IDC_SORT_R                      1004
#define IDC_INPUT_PERCENT               1004
#define IDC_EDIT_START                  1004
#define IDC_PAINT_NO                    1004
#define IDC_EDIT_PORT                   1004
#define IDC_TIME_HOUR                   1004
#define IDC_MAP_X                       1004
#define EDT_MAP_NAME                    1004
#define EDT_LOCALEND                    1004
#define EDT_ENDTIME                     1004
#define EDT_POSY                        1004
#define IDC_POSY                        1004
#define IDC_Y                           1004
#define IDC_RADIO8                      1005
#define IDC_EDIT_ITEM_Y                 1005
#define IDC_ALL_AFFECT_NO               1005
#define IDC_EDIT_END                    1005
#define IDC_RADIO_FISH                  1005
#define IDC_EDIT_IP                     1005
#define IDC_TIME_MINUTE                 1005
#define IDC_MAP_Y                       1005
#define IDC_RADIO4                      1006
#define IDC_EDIT_MOX                    1006
#define IDC_EDIT_OFFX                   1006
#define IDC_RADIO_CHOPPING              1006
#define IDC_SHADOW_NO                   1006
#define IDC_RADIO2                      1007
#define IDC_EDIT_MOY                    1007
#define IDC_EDIT_OFFY                   1007
#define IDC_RADIO_HUB                   1007
#define IDC_RADIO_1_ONESWORD            1008
#define IDC_RADIO9                      1008
#define IDC_RADIO_ANI1                  1008
#define IDC_RADIO_NPC                   1008
#define IDC_EDIT3                       1009
#define IDC_RADIO_1_TWOSWORD            1009
#define IDC_RADIO_ANI2                  1009
#define IDC_CURFRAME                    1009
#define IDC_EDIT_MAPX                   1009
#define IDC_TITLE                       1009
#define EDT_XPOS                        1009
#define IDC_RADIO_1_PENSING             1010
#define IDC_RADIO_ANI3                  1010
#define IDC_EDIT_MAPY                   1010
#define EDT_YPOS                        1010
#define IDC_RADIO_1_BONG                1011
#define IDC_RADIO_ANI4                  1011
#define IDC_RADIO_ANI5                  1012
#define IDC_RADIO5                      1013
#define IDC_RADIO_OUT0                  1013
#define IDC_RADIO10                     1014
#define IDC_RADIO_OUT1                  1014
#define IDC_CHECK_SOUND                 1015
#define IDC_RADIO11                     1015
#define IDC_RADIO_OUT2                  1015
#define IDC_CHECK_EFFECT_WAVE           1016
#define IDC_RADIO12                     1016
#define IDC_RADIO_OUT3                  1016
#define IDC_CHECK_SUPER_HERO            1017
#define IDC_RADIO13                     1017
#define IDC_RADIO_SPRITE0               1017
#define IDC_CHECK_READ_CDDATA           1018
#define IDC_RADIO14                     1018
#define IDC_RADIO_SPRITE1               1018
#define IDC_CHECK_ONE_KILL              1019
#define IDC_RADIO_SPRITE2               1019
#define IDC_CHECK_DEBUGINFO             1020
#define IDC_CHECK_CONECT_SERVER         1021
#define IDC_CHECK_GAMEMAKEMODE          1022
#define IDC_RADIO_LIGHT_0               1022
#define IDC_CHECK_WEATHER_NIGHT         1023
#define IDC_RADIO_LIGHT_1               1023
#define IDC_EDIT1                       1024
#define IDC_RADIO_LIGHT_2               1024
#define IDC_LOAD_ITEM_FROM_TOI2         1024
#define IDC_EDIT4                       1025
#define IDC_RADIO_LIGHT_3               1025
#define IDC_ENTER_GAMESERVER            1025
#define IDC_EDIT5                       1026
#define IDC_RADIO_LIGHT_4               1026
#define IDC_ENTER_LOGINIP               1026
#define IDC_ENTER_AGENTIP               1026
#define IDC_RADIO_1_MALE                1027
#define IDC_EDIT_ANITYPE                1027
#define IDC_RADIO_LIGHT_5               1027
#define IDC_VIEW_EY                     1027
#define IDC_ABILIT_WIS                  1027
#define IDC_IMSI1                       1027
#define IDC_TAC_FENCING                 1027
#define IDC_MAKE_SOU2_SIZE              1027
#define IDC_WAIT2                       1027
#define IDC_EDIT6                       1027
#define IDC_RADIO_1_NO                  1028
#define IDC_EDIT_SORTR_Y                1028
#define IDC_VIEW_TILENUM                1028
#define IDC_ABILIT_INT                  1028
#define IDC_IMSI2                       1028
#define IDC_TAC_MACE                    1028
#define IDC_ENTER_PROXYIP               1028
#define IDC_START3                      1028
#define IDC_EDIT13                      1028
#define IDC_CHECK_ENABLE_MENU           1029
#define IDC_RADIO_LIGHT_6               1029
#define IDC_VIEW_OBJECTNUM              1029
#define IDC_ABILIT_CHA                  1029
#define IDC_TAC_PIERCE                  1029
#define IDC_WAIT3                       1029
#define IDC_CHECK_VIEWCHARACTERFRAME    1030
#define IDC_RADIO_LIGHT_7               1030
#define IDC_ABILIT_MOVP                 1030
#define IDC_TAC_WHIRL                   1030
#define IDC_RADIO_LIGHT_8               1031
#define IDC_SAVE_ANIMATION_TABLE        1031
#define IDC_ABILIT_ENDU                 1031
#define IDC_TAC_HURL                    1031
#define IDC_RADIO_LIGHT_9               1032
#define IDC_ABILIT_MOR                  1032
#define IDC_TAC_PARRYING                1032
#define IDC_KEY_RECORD                  1032
#define IDC_RADIO_LIGHT_10              1033
#define IDC_ABILIT_LUCK                 1033
#define IDC_TAC_DSWORD                  1033
#define IDC_KEY_PLAY                    1033
#define IDC_BUTTON1                     1034
#define IDC_RADIO_LIGHT_11              1034
#define IDC_ABILIT_WSPS                 1034
#define IDC_TAC_DMACE                   1034
#define IDC_MAP_SCROLL_TYPE             1034
#define IDC_BUTTON2                     1035
#define IDC_RADIO_LIGHT_12              1035
#define IDC_ABILIT_MONEY                1035
#define IDC_TAC_MAGERY                  1035
#define IDC_BUTTON3                     1036
#define IDC_RADIO_LIGHT_13              1036
#define IDC_ABILIT_LVPOINT              1036
#define IDC_TAC_ORISON                  1036
#define IDC_BUTTON4                     1037
#define IDC_RADIO_LIGHT_14              1037
#define IDC_TAC_FENCING2                1037
#define IDC_BUTTON5                     1038
#define IDC_EDIT7                       1038
#define IDC_RADIO_LIGHT_15              1038
#define IDC_TAC_MACE2                   1038
#define IDC_BUTTON6                     1039
#define IDC_EDIT8                       1039
#define IDC_RADIO_LIGHT_16              1039
#define IDC_TAC_PIERCE2                 1039
#define IDC_BUTTON7                     1040
#define IDC_EDIT9                       1040
#define IDC_RADIO_LIGHT_17              1040
#define IDC_TAC_WHIRL2                  1040
#define IDC_BUTTON8                     1041
#define IDC_EDIT10                      1041
#define IDC_TAC_HURL2                   1041
#define IDC_PRI_ANIMATION               1042
#define IDC_EDIT11                      1042
#define IDC_X_R2                        1042
#define IDC_TAC_PARRYING2               1042
#define IDC_NEXT_ANIMATION              1043
#define IDC_EDIT12                      1043
#define IDC_ORI_UU                      1043
#define IDC_TAC_DSWORD2                 1043
#define IDC_CHARACTER_LOAD              1044
#define IDC_DONTBOX_D1                  1044
#define IDC_TAC_DMACE2                  1044
#define ID_ANIMATION_SAVE               1045
#define IDC_DONTBOX_L1                  1045
#define IDC_TAC_MAGERY2                 1045
#define IDC_ANI_TITLE                   1046
#define IDC_DONTBOX_R1                  1046
#define IDC_TAC_ORISON2                 1046
#define IDC_DONTBOX_D2                  1047
#define IDC_CHAR_NO                     1048
#define IDC_DONTBOX_L2                  1048
#define IDC_PLAY_ANIMATION              1049
#define IDC_DONTBOX_R2                  1049
#define ID_ANIMATION_LOAD               1050
#define IDC_DONTBOX_D3                  1050
#define IDC_CHECK_1_VIEW_PART           1051
#define IDC_DONTBOX_L3                  1051
#define EDT_CHAR_MUTANT                 1051
#define IDC_ANI_EDIT                    1052
#define IDC_DONTBOX_R3                  1052
#define IDC_EDIT_CLOTH1                 1053
#define IDC_EDIT_ACC0                   1053
#define IDC_DONTBOX_D4                  1053
#define IDC_EDIT_CLOTH2                 1054
#define IDC_EDIT_ACC1                   1054
#define IDC_DONTBOX_L4                  1054
#define IDC_EDIT_CLOTH3                 1055
#define IDC_EDIT_ACC2                   1055
#define IDC_DONTBOX_R4                  1055
#define IDC_CHANGE_EQUIP                1056
#define IDC_SAVE                        1057
#define IDC_EDIT_ACC3                   1057
#define IDC_EDIT_ID                     1058
#define IDC_EDIT_X                      1059
#define IDC_EDIT_LEVEL                  1059
#define IDC_EDIT_Y                      1060
#define IDC_EDIT_EXP                    1060
#define IDC_EDIT_OFFSETX                1061
#define IDC_EDIT_HP                     1061
#define IDC_EDIT_OFFSETY                1062
#define IDC_EDIT_BASIC                  1062
#define IDC_EDIT_MANA                   1062
#define IDC_FRAME_UP                    1063
#define IDC_FRAME_DOWN                  1064
#define IDC_EDIT_CURFRAME               1065
#define IDC_FRAME_UP2                   1066
#define IDC_MAPNAME                     1066
#define IDC_FRAME_DOWN2                 1067
#define IDC_LOGINIP                     1067
#define IDC_AGENTIP                     1067
#define IDC_EDIT_SERVER_ID              1068
#define IDC_PROXYIP                     1068
#define IDC_RADIO_ANI0                  1070
#define IDC_EDIT_ANITYPE_               1071
#define IDC_EDIT_OUT_                   1072
#define IDC_EDIT_SPRITE_                1073
#define IDC_BUTTON_OFF_LEFT             1074
#define IDC_BUTTON_OFF_RIGHT            1075
#define IDC_BUTTON_OFF_DOWN             1076
#define IDC_BUTTON_OFF_UP               1077
#define IDC_BUTTON_SAVE                 1078
#define IDC_BUTTON_SORTL_L              1079
#define IDC_BUTTON_SORTL_R              1080
#define IDC_BUTTON_SORTL_U              1081
#define IDC_BUTTON_SORTL_D              1082
#define IDC_BUTTON_SORTR_L              1083
#define IDC_BUTTON_SORTR_U              1084
#define IDC_BUTTON_SORTR_R              1085
#define IDC_BUTTON_SORTR_D              1086
#define IDC_EDIT_SORTL_X                1087
#define IDC_EDIT_SORTL_Y                1088
#define IDC_EDIT_SORTR_X                1089
#define IDC_BUTTON_LIGHT_U              1090
#define IDC_BUTTON_LIGHT_L              1091
#define IDC_BUTTON_LIGHT_R              1092
#define IDC_BUTTON_LIGHT_D              1093
#define IDC_BUTTON_SORTL_L2             1101
#define IDC_BUTTON_SORTL_R2             1102
#define IDC_BUTTON_SORTL_U2             1103
#define IDC_BUTTON_SORTL_D2             1104
#define IDC_BUTTON_SORTR_L2             1105
#define IDC_BUTTON_SORTR_R2             1106
#define IDC_BUTTON_SORTR_U2             1107
#define IDC_BUTTON_SORTR_D2             1108
#define IDC__ANI6                       1109
#define IDC__ANI7                       1110
#define IDC__ANI8                       1111
#define IDC__ANI9                       1112
#define IDC__ANI10                      1113
#define IDC__ANI11                      1114
#define IDC_RADIO_ITEM_YES2             1115
#define IDC_X_L                         1115
#define IDC_RADIO_ITEM_NO2              1116
#define IDC_Y_U                         1116
#define IDC_RADIO_ITEM_YES3             1117
#define IDC_RADIO_ITEM_NO3              1118
#define IDC_Y_D                         1119
#define IDC_X_R                         1120
#define IDC_X_L2                        1121
#define IDC_Y_U2                        1122
#define IDC_Y_D2                        1123
#define IDC_ITEM_CHAIR                  1124
#define IDC_ITEM_TABLE                  1125
#define IDC_ITEM_DOOR                   1126
#define IDC_ITEM_BOX                    1127
#define IDC_ITEM_NORMAL                 1128
#define IDC_CURFRAME_DOWN               1129
#define IDC_CURFRAME_UP                 1130
#define IDC_ITEM_SIGNBOARD              1131
#define IDC_EDIT_ALPHA                  1132
#define IDC_ITEM_DIRECTBOARD            1133
#define IDC_ORI_L                       1134
#define IDC_ORI_R                       1135
#define IDC_ORI_RR                      1136
#define IDC_ORI_D                       1137
#define IDC_ORI_DD                      1138
#define IDC_ORI_U                       1139
#define IDC_ORI_LL                      1140
#define IDC_ATTR_RIVER                  1145
#define IDC_ATTR_DONT                   1146
#define IDC_DONT_TO_GE                  1147
#define IDC_ATTR_GEFFECT                1148
#define IDC_ATTR_OFFSET_YES             1149
#define IDC_ATTR_INSIDE                 1149
#define IDC_ATTR_OFFSET_NO              1150
#define IDC_ATTR_NO_BATTLE              1150
#define IDC_BRUSH1                      1151
#define IDC_ATTR_CANMATCH               1151
#define IDC_SOURCE_AFFECT_YES           1152
#define IDC_ALL_AFFECT                  1152
#define IDC_SOURCE_AFFECT_NO            1153
#define IDC_INPUT_TILE_X                1153
#define IDC_SHADOW_YES                  1153
#define IDC_ATTR_OFFSET_YES2            1154
#define IDC_INPUT_TILE_Y                1154
#define IDC_ATTR_OFFSET_NO2             1155
#define IDC_VIEW_ATTRIB                 1155
#define IDC_INPUT_RANGE                 1156
#define IDC_DEPAINT_YES                 1156
#define IDC_FARMING                     1157
#define IDC_DEPAINT_NO                  1157
#define IDC_MINING                      1158
#define IDC_ATTR_TOP                    1158
#define IDC_BUTTON_UP                   1159
#define IDC_ATTR_OCCUPIED               1159
#define IDC_FISHING                     1160
#define IDC_CHOPPING                    1161
#define IDC_HUB                         1162
#define IDC_BUTTON_DOWN                 1163
#define IDC_NPC_GENER                   1164
#define IDC_ITEM_NORMAL4                1164
#define IDC_VIEW_NPCNUM                 1165
#define IDC_ITEM_CHAIR4                 1165
#define IDC_MINER10                     1166
#define IDC_ITEM_TABLE4                 1166
#define IDC_MINER1                      1167
#define IDC_ITEM_DOOR4                  1167
#define IDC_PLUS1                       1168
#define IDC_ITEM_BOX4                   1168
#define IDC_PLUS10                      1169
#define IDC_ITEM_SIGNBOARD4             1169
#define IDC_MONSTER_NAME                1170
#define IDC_ITEM_DIRECTBOARD4           1170
#define IDC_VIEW_SUBFARM                1171
#define IDC_ITEM_WORKTABLE_MORU4        1171
#define IDC_VIEW_SUBMINE                1172
#define IDC_ITEM_WORKTABLE_HWADUK4      1172
#define IDC_FARM_PLUS                   1173
#define IDC_ITEM_WORKTABLE_SIHUMKWAN4   1173
#define IDC_FARM_MINER                  1174
#define IDC_MINE_PLUS                   1175
#define IDC_MINE_MINER                  1176
#define IDC_VIEW_SUBHUB                 1177
#define IDC_ITEM_WORKTABLE_MINING4      1177
#define IDC_HUB_PLUS                    1178
#define IDC_ITEM_WORKTABLE_BATTLE4      1178
#define IDC_HUB_MINER                   1179
#define IDC_ITEM_WORKTABLE_SUNBAN4      1179
#define IDC_DONTSKILL                   1180
#define IDC_ITEM_WORKTABLE_MULAE4       1180
#define IDC_MINER_PERCENT               1181
#define IDC_ITEM_WORKTABLE_BULDAE4      1181
#define IDC_PLUS_PERCENT                1182
#define IDC_ITEM_SEAL_NOR               1182
#define IDC_CURSOR_DOWN                 1183
#define IDC_SCRIPT_NO                   1183
#define IDC_ITEM_SEAL_SPC               1183
#define IDC_CURSOR_UP                   1184
#define IDC_GENER_NO                    1184
#define IDC_OFF_L                       1185
#define IDC_NPCNO_UP                    1185
#define IDC_OFF_R                       1186
#define IDC_NPCNO_DOWN                  1186
#define IDC_OFF_D                       1187
#define IDC_SCRIPT_MINER10              1187
#define IDC_ITEM_HP_UP                  1187
#define IDC_OFF_U                       1188
#define IDC_SCRIPT_MINER1               1188
#define IDC_ITEM_MP_UP                  1188
#define IDC_CURSOR_NO                   1189
#define IDC_SCRIPT_PLUS1                1189
#define IDC_ITEM_NATION_STONE           1189
#define IDC_PAINT_YES                   1190
#define IDC_SCRIPT_PLUS10               1190
#define IDC_ITEM_GUILD_STONE            1190
#define IDC_IO_D10                      1191
#define IDC_BUILD_HOUSE                 1191
#define IDC_ITEM_SP_UP                  1191
#define IDC_IO_D1                       1192
#define IDC_VIEW_SUBFISH                1192
#define IDC_ITEM_SENARIO_STONE          1192
#define IDC_IO_U1                       1193
#define IDC_FISH_PLUS                   1193
#define IDC_ITEM_COLOSSUS_STONE         1193
#define IDC_IO_U10                      1194
#define IDC_FISH_MINER                  1194
#define IDC_EDIT_OBJECT_NO              1195
#define IDC_VIEW_SUBCUT                 1195
#define IDC_IO_U100                     1196
#define IDC_CUT_PLUS                    1196
#define IDC_IO_D100                     1197
#define IDC_CUT_MINER                   1197
#define IDC_VIEW_SX                     1198
#define IDC_IO_U1000                    1198
#define IDC_VIEW_SY                     1199
#define IDC_IO_D1000                    1199
#define IDC_VIEW_EX                     1200
#define IDC_RADIO_ALL                   1201
#define IDC_EDIT_ITEM_IN_BOX            1202
#define IDC_RADIO_HOUSE                 1202
#define IDC_ABILIT_STR                  1203
#define IDC_EDIT_OBJECT_SOUND_NO        1203
#define IDC_ABILIT_DEX                  1204
#define IDC_EDIT_OBJECT_SOUND_FRAME     1204
#define IDC_ABILIT_CON                  1205
#define IDC_EDIT_OBJECT_SOUND_DEALY     1205
#define IDC_UPDATE                      1206
#define IDC_EDIT_OBJECT_FRAME           1206
#define IDC_TYPE                        1207
#define IDC_NUMBER                      1208
#define IDC_DURATION                    1209
#define IDC_GENER_ITEM_NUM              1213
#define IDC_DONTBOX_U1                  1214
#define IDC_DONTBOX_U2                  1215
#define IDC_DELETE_TYPE                 1215
#define IDC_DONTBOX_U3                  1216
#define IDC_DELETE_UP                   1216
#define IDC_DONTBOX_U4                  1217
#define IDC_DELETE_DOWN                 1217
#define IDC_DELETE_BUTTON               1218
#define IDC_TAC_CRAPPLE                 1220
#define IDC_TAC_SWORD                   1221
#define IDC_TAC_ARCHERY                 1222
#define IDC_TAC_CRAPPLE2                1223
#define IDC_TAC_SWORD2                  1224
#define IDC_TAC_ARCHERY2                1225
#define IDC_CONVERT                     1226
#define IDC_EDIT_TOOL_PW                1227
#define ID_NPC_ALL_DELETE               1228
#define ID_NPC_CHANGE                   1229
#define IDC_EDIT_FROM                   1230
#define IDC_EDIT_TO                     1231
#define ID_SOUND_PLAY                   1232
#define IDC_OBS_OVERLAP                 1233
#define IDC_SKILL_EDIT_0                1233
#define IDC_OBS_3TYPE                   1234
#define IDC_SKILL_EDIT_1                1234
#define IDC_EDIT_CHARACTER_NAME         1234
#define IDC_OBS_ETC                     1235
#define IDC_SKILL_EDIT_2                1235
#define IDC_EDIT_MAP_NAME               1235
#define IDC_SKILL_EDIT_3                1236
#define IDC_EDIT_MAP_FILE               1236
#define IDC_SKILL_EDIT_4                1237
#define IDC_SKILL_EDIT_5                1238
#define IDC_SKILL_EDIT_6                1239
#define IDC_BUTTON_GOTO_HIM             1239
#define IDC_SKILL_EDIT_7                1240
#define IDC_TAB1                        1240
#define IDC_SKILL_EDIT_8                1241
#define IDC_COMBO1                      1241
#define CBO_MAPNAME                     1241
#define CBO_NAME                        1241
#define CBO_SCENARIO_NAME               1241
#define CBO_WAR_STATUS                  1241
#define IDC_SKILL_EDIT_9                1242
#define IDC_PLUS_EQUIP                  1242
#define IDC_TU_LOG                      1242
#define IDC_SKILL_EDIT_10               1243
#define IDC_SKILL_EDIT_11               1244
#define IDC_SKILL_EDIT_12               1245
#define IDC_SKILL_EDIT_13               1246
#define IDC_SKILL_EDIT_14               1247
#define IDC_SKILL_EDIT_15               1248
#define IDC_LIST_TITLE                  1248
#define IDC_SKILL_EDIT_16               1249
#define IDC_RICHEDIT_TITLE              1249
#define IDC_SKILL_EDIT_17               1250
#define IDC_OPEN_MAP                    1250
#define IDC_SKILL_EDIT_18               1251
#define IDC_START_EVENT                 1251
#define IDC_SKILL_EDIT_19               1252
#define IDC_END_EVENT                   1252
#define IDC_SKILL_EDIT_20               1253
#define IDC_CLOSE_MAP                   1253
#define IDC_SKILL_EDIT_21               1254
#define IDC_RADIO_O                     1254
#define IDC_SKILL_EDIT_22               1255
#define IDC_QUESTION                    1255
#define IDC_SKILL_EDIT_23               1256
#define IDC_SEND_QUESTION               1256
#define IDC_SKILL_EDIT_24               1257
#define IDC_ANSER                       1257
#define IDC_SKILL_EDIT_25               1258
#define IDC_SET_TIME                    1258
#define IDC_SKILL_EDIT_26               1259
#define CHK_NPC_HEADER                  1259
#define IDC_TARGET_NAME                 1259
#define IDC_SKILL_EDIT_27               1260
#define CHK_NPC_BODY                    1260
#define IDC_MAP_NAME                    1260
#define IDC_LIST1                       1260
#define LST_SELECTED_USERS              1260
#define LST_SCHEDULE                    1260
#define IDC_LOCALWARSCHEDULE            1260
#define IDC_SKILL_EDIT_28               1261
#define CHK_NPC_WEAPON                  1261
#define IDC_START1                      1261
#define IDC_SKILL_EDIT_29               1262
#define CHK_EFFECT_ONE                  1262
#define IDC_WAIT1                       1262
#define IDC_SKILL_EDIT_30               1263
#define CHK_EFFECT_TWO                  1263
#define IDC_START2                      1263
#define IDC_SKILL_EDIT_31               1264
#define LST_UNSELECTED                  1264
#define IDC_SKILL_EDIT_32               1265
#define BTN_DEL_USER                    1265
#define IDC_SKILL_EDIT_33               1266
#define BTN_ENABLE_USER                 1266
#define IDC_SKILL_EDIT_34               1267
#define BTN_ENABLE_USER_ALL             1267
#define BTN_DEL_USER_ALL                1268
#define BTN_REFRESH                     1269
#define EDT_NAME                        1270
#define BTN_LISTSAVE                    1270
#define BTN_ADD_USER                    1271
#define IDC_TU_LOG_CLEAR                1271
#define BTN_MOVE                        1272
#define BTN_LOGOUT                      1273
#define BTN_RESCURE                     1274
#define BTN_MAKE_GHOST                  1275
#define CHK_ZYPERN                      1276
#define CHK_YLLSE                       1277
#define CHK_VISEUS                      1278
#define EDT_SPRNO                       1279
#define BTN_IMPRISON                    1279
#define EDT_LOCALSTART                  1280
#define BTN_RELEASE                     1280
#define EDT_STARTTIME                   1281
#define CBO_WAR_FIELD_NAME              1282
#define EDT_LOOP_TIME                   1283
#define EDT_ENDMIN                      1284
#define EDT_STARTMIN                    1285
#define EDT_POSX                        1286
#define IDC_POSX                        1286
#define CHE_PARENT                      1287
#define CHE_CURRENT                     1288
#define IDC_BARANTAN                    1288
#define CHE_MAX                         1289
#define IDC_RENUS                       1289
#define CHE_AVR                         1290
#define IDC_HELTERNT                    1290
#define CHE_MIN                         1291
#define IDC_AMOUNT                      1291
#define CHE_RATE                        1292
#define IDC_CURPOS                      1292
#define IDC_GRADE                       1292
#define IDC_SPREAD                      1293
#define IDC_LEGENDNO                    1293
#define IDC_SUMMON                      1294
#define IDC_CLASSTYPE                   1294
#define IDC_AMOUNT2                     1295
#define IDC_DROPS                       1296
#define IDC_KILLALL                     1298
#define IDC_REMOVENK                    1299
#define IDC_AMOUNT3                     1299
#define IDC_SPRITENO                    1300
#define IDC_SPAWN_SARD                  1301
#define IDC_START                       1302
#define IDC_JOIN                        1303
#define IDC_SKILL_EDIT_35               1305
#define IDC_LVLMIN                      1305
#define IDC_SKILL_EDIT_36               1306
#define IDC_LVLMAX                      1306
#define IDC_SKILL_EDIT_37               1307
#define IDC_SETLVL                      1307
#define IDC_SKILL_EDIT_38               1308
#define IDC_CLEAR                       1308
#define IDC_SKILL_EDIT_39               1309
#define IDC_MULTIPLIER                  1309
#define IDC_SKILL_EDIT_40               1310
#define IDC_DAY1                        1310
#define IDC_SKILL_EDIT_41               1311
#define IDC_DAY2                        1311
#define IDC_SKILL_EDIT_42               1312
#define IDC_DAY3                        1312
#define IDC_SKILL_EDIT_43               1313
#define IDC_DAY4                        1313
#define IDC_DAY5                        1314
#define IDC_DAY6                        1315
#define IDC_DAY7                        1316
#define IDC_APPLY                       1317
#define IDC_RESETEXP                    1318
#define IDC_ENPK                        1319
#define IDC_ENBATTLE                    1320
#define IDC_DISPK                       1321
#define IDC_DISBATTLE                   1322
#define IDC_CHECK1                      1323
#define IDC_X                           1324
#define IDC_ADD                         1325
#define IDC_FORCE                       1326
#define IDC_RICHEDIT22                  1328
#define ID_BAN                          1329
#define ID_UNBAN                        1330
#define ID_CLOSE_BAN_TOOL               1331
#define ID_UNBAN2                       1332
#define ID_ACCOUNT_LOCK                 1332
#define IDC_ITEM                        1332
#define GENERATEOK                      1333
#define IDC_ISDYNAMIC                   1338
#define CBO_RARE1                       1339
#define CBO_RARE2                       1340
#define CBO_RARE3                       1341
#define CBO_DYNAMIC                     1342
#define IDC_ISLOCALWAR                  1343
#define IDC_ISLEGEND                    1343
#define IDC_ISHIGH                      1344
#define IDC_TU_OFF                      1344
#define CBO_RARE4                       1345
#define IDC_TU_ON                       1345
#define IDC_ISRARE                      1346
#define EDT_TU_NAME                     1346
#define IDC_ISRARE2                     1347
#define IDC_ISNORMAL                    1347
#define CBO_RARE5                       1348
#define CBO_ITEMGEN_NAME                1348
#define CBO_ITEMGEN_NAME2               1349
#define ID_CHECK_ANIMATION              32771
#define ID_CHECK_CLOTH_ORDER            32772
#define ID_EVENT_SCRIPT_SAVE            32773
#define ID_EVENT_SCRIPT                 32773
#define ID_VIEW_ATTR_EVENT              32774
#define ID_CHANGE_BODYRGB               32775
#define ID_VIEW_ANIMATION_FRAME         32776
#define ID_DRAWMAP                      32777
#define ID_MULTICHAR                    32778
#define ID_FRAMECHECK                   32779
#define ID_VIEW_NIGHT                   32780
#define ID_VIEW_RAIN                    32781
#define ID_VIEW_SNOW                    32782
#define ID_VIEW_ATTR_DONT               32783
#define ID_VIEW_NIGHT0                  32784
#define ID_VIEW_NIGHT10                 32785
#define ID_VIEW_NIGHT11                 32785
#define ID_VIEW_NIGHT20                 32786
#define ID_VIEW_NIGHT21                 32786
#define ID_VIEW_NIGHT30                 32787
#define ID_MAPOBJECT_MODIFY             32788
#define ID_VIEW_ATTR_FRONT              32789
#define ID_SYSINFO_GAMEMAKEMODE         32790
#define ID_HERO_POSITION_SETTING        32791
#define ID_VIEW_NIGHT5                  32792
#define ID_VIEW_NIGHT3                  32793
#define ID_VIEW_NIGHT7                  32794
#define ID_VIEW_NIGHT9                  32795
#define ID_VIEW_NIGHT13                 32796
#define ID_VIEW_NIGHT15                 32797
#define ID_VIEW_NIGHT17                 32798
#define ID_VIEW_NIGHT19                 32799
#define ID_VIEW_NIGHT23                 32800
#define ID_VIEW_NIGHT25                 32801
#define ID_VIEW_ATTR_SHOW_ROOF          32802
#define ID_MENUITEM32803                32803
#define ID_INPUT_SKILL                  32803
#define ID_INPUT_MAP_ATTR               32804
#define ID_VIEW_ATTR_GEFFECT            32805
#define ID_VIEW_ATTR_RIVER              32806
#define ID_CHECK_TILE_ATTR              32807
#define ID_MOUSECURSOR_CHECK            32808
#define ID_VIEW_ATTR_INSIDE             32809
#define ID_DRAWROOFMAP                  32810
#define ID_EFFECT_TEST                  32811
#define ID_INPUT_MAPOBJECT_MENU         32812
#define ID_INPUT_MYHOUSE                32813
#define ID_OUTPUT_MYHOUSE               32814
#define ID_CHARACTER_LIST               32815
#define ID_GENERATE_ITEM                32816
#define ID_SIGHT_VIEW_NORMAL            32817
#define ID_SIGHT_VIEW_WIDER             32818
#define IDD_SMALL_RADAR                 32819
#define ID_PATHFIND_1                   32820
#define ID_PATHFIND_2                   32821
#define ID_PATHFIND_3                   32822
#define ID_PATHFIND_4                   32823
#define ID_PATHFIND_5                   32824
#define ID_PATHFIND_0                   32825
#define ID_DRAWOBJECT                   32826
#define ID_DRAWFRONTMAP                 32827
#define ID_VIEW_ATTR_NO_BATTLE          32828
#define ID_CHANGE_TACTICS               32829
#define ID_COUNSELER_MOVE               32830
#define ID_COUNSELER_ATTACK             32831
#define ID_COUNSELER_MAGIC              32832
#define ID_COUNSELER_AB_MOVE            32833
#define ID_SOUND_FESTIVAL               32835
#define ID_SOUND_HANDCLAP               32836
#define ID_ABSOLUTE_LOGOUT              32837
#define ID_MAKE_GHOST                   32838
#define ID_GIVE_LIFE                    32839
#define ID_OUTPUT_CELEBRATE             32840
#define ID_VIEW_ATTR_OCCUPIED           32841
#define ID_TOOL_PW                      32842
#define ID_TRIP_AROUND_ON               32843
#define ID_TRIP_AROUND_OFF              32844
#define ID_VIEW_ATTR_CANMATCH           32845
#define ID_INPUT_SKILL_NPC_DELETE       32846
#define ID_SERVER_ITEMTABLE_RELOAD      32847
#define ID_MESSAGE                      32848
#define ID_PUBLIC_MESSAGE_IN_MAP        32848
#define ID_CHANGE_SKILL_EXP             32849
#define ID_SERVER_NPC_ACCESS_TABLE_RELOAD 32850
#define ID_COUNSELER_AB_MOVE_DUNGEON_KEEPER 32851
#define ID_TEAM_BATTLE_START            32852
#define ID_TEAM_BATTLE_END              32853
#define IDD_MY_SKILL_EXP                32854
#define IDD_SMALL_RADAR_FARM            32855
#define IDD_SMALL_RADAR_MINING          32856
#define IDD_SMALL_RADAR_FISHING         32857
#define IDD_SMALL_RADAR_CUTTING         32858
#define IDD_SMALL_RADAR_HUB             32859
#define IDD_SMALL_RADAR_NPC             32860
#define IDD_SMALL_RADAR_ITEM_SEAL       32862
#define ID_RESET_VOTE                   32863
#define ID_WHERE_IS_HE                  32864
#define ID_PUBLIC_MESSAGE_IN_MAP_ALL    32865
#define ID_DONT_VIEW_MESSAGE            32866
#define ID_DONT_VIEW_CHAT               32867
#define ID_DONT_VIEW_DAMAGE_NUMBER      32868
#define ID_DONT_VIEW_MAIN_INTERFACE     32869
#define ID_CHECK_EFFECT                 32870
#define ID_RESET_MENU                   32871
#define ID_RESET_SMALL_MENU             32872
#define IDM_VIEW_GUILD                  32873
#define IDM_RELOAD_MENU_DATA            32874
#define IDM_LOGOUT_NAME                 32876
#define ID_START_EVENT                  32877
#define ID_MENU_MOVE_MAP                32878
#define ID_OTHER_CHAR_INFO              32879
#define ID_COUNSELER_SKILL              32880
#define ID_MENUITEM_SET_SCENARIO        32881
#define ID_MENU_MOVE_MAP_MULTIPLE       32882
#define ID_MOSTER_GENERATER             32883
#define ID_LOCALWAR                     32885
#define ID_NATIONSET                    32886
#define ID_VIEW_PROFILER                32888
#define ID_CHANGE_FONT                  32889
#define ID_GM_MOVETOCHARACTER           32890
#define ID_EVENT_LMSJOINTEAM            32891
#define ID_EVENT_LMSSTART               32892
#define ID_PLAY_SOUND                   32893
#define ID_GM_ENABLE                    32894
#define ID_EVENT_LMSMENU                32895
#define ID_EVENT_DOUBLEEXP              32896
#define ID_EVENT_EXP                    32897
#define ID_EVENT_ENABLE                 32898
#define ID_EVENT_PK                     32899
#define ID_CHECK_ADDSELFINQUEST         32900
#define ID_CHECK_QUEST                  32901
#define ID_GM_BANTOOL                   32902
#define ID_GM1_BANTOOL                  32903
#define ID_GM1_ENABLE                   32904
#define ID_COUNSELER_ANTI_TEAM          32905
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         32907
#define _APS_NEXT_CONTROL_VALUE         1350
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
